import Link from "next/link"

import { Button } from "@/components/ui/button"
import {
  Empty,
  EmptyContent,
  EmptyDescription,
  EmptyHeader,
  EmptyTitle,
} from "@/components/ui/empty"

// The shared body of every not-found boundary, so a second one cannot drift from the first. Callers own the surroundings: the app-level boundary renders outside any shell and supplies the main landmark, while the console's renders inside one that already has it.
// aria-level rather than an h1 because EmptyTitle is a div and ui/* is regenerated by the shadcn sync; this gives the page its one top-level heading without forking the primitive.
export function RouteNotFound({
  action,
  className,
  description,
  href,
  title,
}: {
  action: string
  className?: string
  description: string
  href: string
  title: string
}) {
  return (
    <Empty className={className}>
      <EmptyHeader>
        <EmptyTitle role="heading" aria-level={1}>
          {title}
        </EmptyTitle>
        <EmptyDescription>{description}</EmptyDescription>
      </EmptyHeader>
      <EmptyContent>
        <Button variant="outline" render={<Link href={href} />}>
          {action}
        </Button>
      </EmptyContent>
    </Empty>
  )
}
