import { join, resolve } from "node:path"

import * as fontkit from "fontkit"
import wawoff2 from "wawoff2"

// Generates the data-table font metrics: per-character advances for the app header font's whole character set plus a sparse kerning-pair table, in px at 500 14px, so any header label (current or future) measures by pure arithmetic on the server and the client alike; nothing touches a canvas and SSR ships final widths. wawoff2 decompresses the woff2 first: fontkit's own woff2 path loses the cmap under getVariation, while the decompressed TTF at wght 500 matches browser canvas metrics exactly.
// Runs in the web/next build, dev, and check-types chains; the output lands in repo-root .generated/ (git-ignored) and is regenerated on every run, so swapping the sans font (see the fonts skill) re-measures automatically. Output depends only on the font file and this script.

const WEB = resolve(import.meta.dir, "../../../web/next")
const FONT = join(WEB, "src/fonts/dm-sans-latin-wght-normal.woff2")
// Mirrors what a header cell actually renders: Table's text-sm (14px) and TableHead's font-medium (500). Restyling either without updating these silently drifts every auto width.
const HEADER_FONT_PX = 14
const HEADER_FONT_WEIGHT = 500
const OUT = resolve(import.meta.dir, "../../../.generated/data-table-metrics.json")

const ttf = Buffer.from(await wawoff2.decompress(await Bun.file(FONT).bytes()))
const base = fontkit.create(ttf)
if ("fonts" in base) throw new Error(`Expected a single font, got a collection: ${FONT}`)
const font = base.getVariation({ wght: HEADER_FONT_WEIGHT })
const shapedPx = (text: string) =>
  (font.layout(text).advanceWidth / font.unitsPerEm) * HEADER_FONT_PX
const round = (px: number) => Math.round(px * 100) / 100

// Every codepoint the font maps, so the calculator covers the full latin subset, not a guessed label list. Full precision internally; rounding happens once at emit.
const exact: Record<string, number> = {}
const advances: Record<string, number> = {}
for (const codePoint of [...base.characterSet].sort((a, b) => a - b)) {
  const char = String.fromCodePoint(codePoint)
  // Zero-advance glyphs (combining marks) are kept as 0; dropping them would fall back to the average and overstate any label that used one.
  const px = shapedPx(char)
  exact[char] = px
  advances[char] = round(px)
}
const values = Object.values(advances)
const average = round(values.reduce((sum, px) => sum + px, 0) / values.length)

// Kerning and two-glyph substitutions as pair deltas over printable ASCII: shaped(ab) minus the two advances. Sparse; anything not listed adjusts by zero, and deltas under 0.05px are dropped as noise the 3-unit width snap can never see.
const kerning: Record<string, number> = {}
const ascii = [...Array(95)].map((_, i) => String.fromCharCode(32 + i))
for (const a of ascii) {
  for (const b of ascii) {
    const delta = shapedPx(a + b) - exact[a] - exact[b]
    if (Math.abs(delta) >= 0.05) kerning[a + b] = round(delta)
  }
}

// The runtime calculator's exact algorithm; a drift here or in data-table.tsx fails the build instead of shipping wrong widths.
function calculatorPx(label: string): number {
  let widthPx = 0
  let previous = ""
  for (const char of label) {
    const advance = advances[char]
    widthPx += advance !== undefined ? advance : average
    if (previous) {
      const pair = kerning[previous + char]
      if (pair !== undefined) widthPx += pair
    }
    previous = char
  }
  return widthPx
}
for (const sample of ["Email Verified", "Joined", "Last Active", "Name", "Role", "Status"]) {
  const calculated = calculatorPx(sample)
  const shaped = shapedPx(sample)
  if (Math.abs(calculated - shaped) > 0.25) {
    throw new Error(`Calculator drift on "${sample}": ${calculated} vs shaped ${shaped}`)
  }
}

const json = `${JSON.stringify(
  {
    $comment: `Generated by packages/scripts/src/data-table-metrics.ts; do not edit. Advances and kerning-pair deltas in px at ${HEADER_FONT_WEIGHT} ${HEADER_FONT_PX}px in the app font.`,
    advances,
    average,
    kerning,
  },
  null,
  2,
)}\n`
const existing = (await Bun.file(OUT).exists()) ? await Bun.file(OUT).text() : ""
if (existing !== json) await Bun.write(OUT, json)
console.log(
  `data-table-metrics: ${values.length} advances, ${Object.keys(kerning).length} kerning pairs`,
)
